// <auto-generated>
//     Generated by the F# GRPC code generator. DO NOT EDIT!
//     source: google/protobuf/duration.proto
// </auto-generated>
namespace rec Google.Protobuf.FSharp.WellKnownTypes
#nowarn "40"
module DurationReflection =
    [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
    let internal Duration_Descriptor() = Descriptor().MessageTypes.[0]
    let private descriptorBackingField: global.System.Lazy<global.Google.Protobuf.Reflection.FileDescriptor> =
        let descriptorData = global.System.Convert.FromBase64String("\
            Ch5nb29nbGUvcHJvdG9idWYvZHVyYXRpb24ucHJvdG8SD2dvb2dsZS5wcm90b2J1ZiI6CghEdXJhdGlv\
            bhIYCgdzZWNvbmRzGAEgASgDUgdzZWNvbmRzEhQKBW5hbm9zGAIgASgFUgVuYW5vc0KDAQoTY29tLmdv\
            b2dsZS5wcm90b2J1ZkINRHVyYXRpb25Qcm90b1ABWjFnb29nbGUuZ29sYW5nLm9yZy9wcm90b2J1Zi90\
            eXBlcy9rbm93bi9kdXJhdGlvbnBi+AEBogIDR1BCqgIeR29vZ2xlLlByb3RvYnVmLldlbGxLbm93blR5\
            cGVzYgZwcm90bzM=")
        global.System.Lazy<_>(
            (fun () ->
                global.Google.Protobuf.Reflection.FileDescriptor.FromGeneratedCode(
                    descriptorData,
                    [|
                    |],
                    new global.Google.Protobuf.Reflection.GeneratedClrTypeInfo(
                        null,
                        null,
                        [|
                            new global.Google.Protobuf.Reflection.GeneratedClrTypeInfo(typeof<global.Google.Protobuf.FSharp.WellKnownTypes.Duration>, global.Google.Protobuf.FSharp.WellKnownTypes.Duration.Parser, [| "Seconds"; "Nanos" |], null, null, null, null)
                        |]
                    )
                )
            ),
            true
        )
    let Descriptor(): global.Google.Protobuf.Reflection.FileDescriptor = descriptorBackingField.Value
type Duration = {
    mutable _UnknownFields: global.Google.Protobuf.UnknownFieldSet
    mutable Seconds: ValueOption<int64>
    mutable Nanos: ValueOption<int32>
} with
    // Start of hand-written code
    static member FromTimeSpan(ts: System.TimeSpan) : Duration =
        let ticks = ts.Ticks
        let seconds = ticks / System.TimeSpan.TicksPerSecond
        let nanos = int ((ticks % System.TimeSpan.TicksPerSecond) * 100L)
        { Duration .empty() with
            Seconds = ValueSome seconds
            Nanos = ValueSome nanos
        }
    member me.ToTimeSpan() : ValueOption<System.TimeSpan> =
        match me.Seconds with
        | ValueNone -> ValueNone
        | ValueSome secs ->
            let nanos = ValueOption.defaultValue 0 me.Nanos
            ValueSome(System.TimeSpan(int64 nanos / 100L + secs * System.TimeSpan.TicksPerSecond))
    // End of hand-written code
    [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
    member me.Clone() : Duration = {
        Duration._UnknownFields = global.Google.Protobuf.UnknownFieldSet.Clone(me._UnknownFields)
        Duration.Seconds = me.Seconds
        Duration.Nanos = me.Nanos
    }
    [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
    member private me.InternalWriteTo(output: byref<global.Google.Protobuf.WriteContext>) =
        if me.Seconds <> ValueNone
        then
            output.WriteRawTag(8uy)
            output.WriteInt64(me.Seconds.Value)
        if me.Nanos <> ValueNone
        then
            output.WriteRawTag(16uy)
            output.WriteInt32(me.Nanos.Value)
        if not <| isNull me._UnknownFields then me._UnknownFields.WriteTo(&output)
    [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
    member private me.CalculateSize() =
        let mutable size = 0
        if me.Seconds <> ValueNone then size <- size + 1 + global.Google.Protobuf.CodedOutputStream.ComputeInt64Size(me.Seconds.Value)
        if me.Nanos <> ValueNone then size <- size + 1 + global.Google.Protobuf.CodedOutputStream.ComputeInt32Size(me.Nanos.Value)
        if not <| isNull me._UnknownFields then size <- size + me._UnknownFields.CalculateSize()
        size
    [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
    member private me.MergeFrom(other: Duration) =
        if other.Seconds <> ValueNone
        then me.Seconds <- other.Seconds
        if other.Nanos <> ValueNone
        then me.Nanos <- other.Nanos
        me._UnknownFields <- global.Google.Protobuf.UnknownFieldSet.MergeFrom(me._UnknownFields, other._UnknownFields)
    [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
    member private me.InternalMergeFrom(input: byref<global.Google.Protobuf.ParseContext>) =
        let mutable tag = input.ReadTag()
        while tag <> 0u do
            match tag with
            | 8u ->
                me.Seconds <- ValueSome(input.ReadInt64())
            | 16u ->
                me.Nanos <- ValueSome(input.ReadInt32())
            | _ ->
                me._UnknownFields <- global.Google.Protobuf.UnknownFieldSet.MergeFieldFrom(me._UnknownFields, &input)
            tag <- input.ReadTag()
    interface global.Google.Protobuf.IBufferMessage with
        [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
        member me.InternalMergeFrom(ctx) = me.InternalMergeFrom(&ctx)
        [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
        member me.InternalWriteTo(ctx) = me.InternalWriteTo(&ctx)
    interface global.Google.Protobuf.IMessage<Duration> with
        [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
        member me.Clone() = me.Clone()
        [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
        member me.MergeFrom(other) = me.MergeFrom(other)
    interface global.Google.Protobuf.IMessage with
        [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
        member me.CalculateSize() = me.CalculateSize()
        [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
        member me.MergeFrom(input) = input.ReadRawMessage(me)
        [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
        member me.WriteTo(output) = output.WriteRawMessage(me)
        [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
        member __.Descriptor = global.Google.Protobuf.FSharp.WellKnownTypes.DurationReflection.Duration_Descriptor()
module Duration =
    [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
    let internal DefaultValue = {
        Duration._UnknownFields = null
        Duration.Seconds = ValueNone
        Duration.Nanos = ValueNone
    }
    [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
    let empty () = {
        Duration._UnknownFields = null
        Duration.Seconds = ValueNone
        Duration.Nanos = ValueNone
    }
    [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
    let Parser = global.Google.Protobuf.MessageParser<Duration>(global.System.Func<_>(empty))
    let SecondsFieldNumber = 1
    let NanosFieldNumber = 2
// End of auto-generated code
