// <auto-generated>
//     Generated by the F# GRPC code generator. DO NOT EDIT!
//     source: google/protobuf/struct.proto
// </auto-generated>
namespace rec Google.Protobuf.FSharp.WellKnownTypes
#nowarn "40"
module StructReflection =
    [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
    let internal Struct_Descriptor() = Descriptor().MessageTypes.[0]
    [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
    let internal Struct_FieldsEntry_Descriptor() = Struct_Descriptor().NestedTypes.[0]
    [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
    let internal Value_Descriptor() = Descriptor().MessageTypes.[1]
    [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
    let internal ListValue_Descriptor() = Descriptor().MessageTypes.[2]
    let private descriptorBackingField: global.System.Lazy<global.Google.Protobuf.Reflection.FileDescriptor> =
        let descriptorData = global.System.Convert.FromBase64String("\
            Chxnb29nbGUvcHJvdG9idWYvc3RydWN0LnByb3RvEg9nb29nbGUucHJvdG9idWYimAEKBlN0cnVjdBI7\
            CgZmaWVsZHMYASADKAsyIy5nb29nbGUucHJvdG9idWYuU3RydWN0LkZpZWxkc0VudHJ5UgZmaWVsZHMa\
            UQoLRmllbGRzRW50cnkSEAoDa2V5GAEgASgJUgNrZXkSLAoFdmFsdWUYAiABKAsyFi5nb29nbGUucHJv\
            dG9idWYuVmFsdWVSBXZhbHVlOgI4ASKyAgoFVmFsdWUSOwoKbnVsbF92YWx1ZRgBIAEoDjIaLmdvb2ds\
            ZS5wcm90b2J1Zi5OdWxsVmFsdWVIAFIJbnVsbFZhbHVlEiMKDG51bWJlcl92YWx1ZRgCIAEoAUgAUgtu\
            dW1iZXJWYWx1ZRIjCgxzdHJpbmdfdmFsdWUYAyABKAlIAFILc3RyaW5nVmFsdWUSHwoKYm9vbF92YWx1\
            ZRgEIAEoCEgAUglib29sVmFsdWUSPAoMc3RydWN0X3ZhbHVlGAUgASgLMhcuZ29vZ2xlLnByb3RvYnVm\
            LlN0cnVjdEgAUgtzdHJ1Y3RWYWx1ZRI7CgpsaXN0X3ZhbHVlGAYgASgLMhouZ29vZ2xlLnByb3RvYnVm\
            Lkxpc3RWYWx1ZUgAUglsaXN0VmFsdWVCBgoEa2luZCI7CglMaXN0VmFsdWUSLgoGdmFsdWVzGAEgAygL\
            MhYuZ29vZ2xlLnByb3RvYnVmLlZhbHVlUgZ2YWx1ZXMqGwoJTnVsbFZhbHVlEg4KCk5VTExfVkFMVUUQ\
            AEJ/ChNjb20uZ29vZ2xlLnByb3RvYnVmQgtTdHJ1Y3RQcm90b1ABWi9nb29nbGUuZ29sYW5nLm9yZy9w\
            cm90b2J1Zi90eXBlcy9rbm93bi9zdHJ1Y3RwYvgBAaICA0dQQqoCHkdvb2dsZS5Qcm90b2J1Zi5XZWxs\
            S25vd25UeXBlc2IGcHJvdG8z")
        global.System.Lazy<_>(
            (fun () ->
                global.Google.Protobuf.Reflection.FileDescriptor.FromGeneratedCode(
                    descriptorData,
                    [|
                    |],
                    new global.Google.Protobuf.Reflection.GeneratedClrTypeInfo(
                        [|
                            typeof<global.Google.Protobuf.FSharp.WellKnownTypes.NullValue>
                        |],
                        null,
                        [|
                            new global.Google.Protobuf.Reflection.GeneratedClrTypeInfo(typeof<global.Google.Protobuf.FSharp.WellKnownTypes.Struct>, global.Google.Protobuf.FSharp.WellKnownTypes.Struct.Parser, [| "Fields" |], null, null, null, [| null |])
                            new global.Google.Protobuf.Reflection.GeneratedClrTypeInfo(typeof<global.Google.Protobuf.FSharp.WellKnownTypes.Value>, global.Google.Protobuf.FSharp.WellKnownTypes.Value.Parser, [| "NullValue"; "NumberValue"; "StringValue"; "BoolValue"; "StructValue"; "ListValue" |], [| "Kind" |], null, null, null)
                            new global.Google.Protobuf.Reflection.GeneratedClrTypeInfo(typeof<global.Google.Protobuf.FSharp.WellKnownTypes.ListValue>, global.Google.Protobuf.FSharp.WellKnownTypes.ListValue.Parser, [| "Values" |], null, null, null, null)
                        |]
                    )
                )
            ),
            true
        )
    let Descriptor(): global.Google.Protobuf.Reflection.FileDescriptor = descriptorBackingField.Value
type NullValue =
| [<global.Google.Protobuf.Reflection.OriginalName("NULL_VALUE")>] NullValue = 0
type Struct = {
    mutable _UnknownFields: global.Google.Protobuf.UnknownFieldSet
    Fields: global.Google.Protobuf.Collections.MapField<string, global.Google.Protobuf.FSharp.WellKnownTypes.Value>
} with
    [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
    member me.Clone() : Struct = {
        Struct._UnknownFields = global.Google.Protobuf.UnknownFieldSet.Clone(me._UnknownFields)
        Struct.Fields = me.Fields.Clone()
    }
    [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
    member private me.InternalWriteTo(output: byref<global.Google.Protobuf.WriteContext>) =
        me.Fields.WriteTo(&output, Struct.MapFieldsCodec)
        if not <| isNull me._UnknownFields then me._UnknownFields.WriteTo(&output)
    [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
    member private me.CalculateSize() =
        let mutable size = 0
        size <- size + me.Fields.CalculateSize(Struct.MapFieldsCodec)
        if not <| isNull me._UnknownFields then size <- size + me._UnknownFields.CalculateSize()
        size
    [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
    member private me.MergeFrom(other: Struct) =
        me.Fields.Add(other.Fields)
        me._UnknownFields <- global.Google.Protobuf.UnknownFieldSet.MergeFrom(me._UnknownFields, other._UnknownFields)
    [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
    member private me.InternalMergeFrom(input: byref<global.Google.Protobuf.ParseContext>) =
        let mutable tag = input.ReadTag()
        while tag <> 0u do
            match tag with
            | 10u ->
                me.Fields.AddEntriesFrom(&input,Struct.MapFieldsCodec)
            | _ ->
                me._UnknownFields <- global.Google.Protobuf.UnknownFieldSet.MergeFieldFrom(me._UnknownFields, &input)
            tag <- input.ReadTag()
    interface global.Google.Protobuf.IBufferMessage with
        [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
        member me.InternalMergeFrom(ctx) = me.InternalMergeFrom(&ctx)
        [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
        member me.InternalWriteTo(ctx) = me.InternalWriteTo(&ctx)
    interface global.Google.Protobuf.IMessage<Struct> with
        [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
        member me.Clone() = me.Clone()
        [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
        member me.MergeFrom(other) = me.MergeFrom(other)
    interface global.Google.Protobuf.IMessage with
        [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
        member me.CalculateSize() = me.CalculateSize()
        [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
        member me.MergeFrom(input) = input.ReadRawMessage(me)
        [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
        member me.WriteTo(output) = output.WriteRawMessage(me)
        [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
        member __.Descriptor = global.Google.Protobuf.FSharp.WellKnownTypes.StructReflection.Struct_Descriptor()
module Struct =
    [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
    let internal DefaultValue = {
        Struct._UnknownFields = null
        Struct.Fields = global.Google.Protobuf.Collections.MapField<string, global.Google.Protobuf.FSharp.WellKnownTypes.Value>()
    }
    [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
    let empty () = {
        Struct._UnknownFields = null
        Struct.Fields = global.Google.Protobuf.Collections.MapField<string, global.Google.Protobuf.FSharp.WellKnownTypes.Value>()
    }
    [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
    let Parser = global.Google.Protobuf.MessageParser<Struct>(global.System.Func<_>(empty))
    let FieldsFieldNumber = 1
    let MapFieldsCodec = global.Google.Protobuf.Collections.MapField<string, global.Google.Protobuf.FSharp.WellKnownTypes.Value>.Codec(global.Google.Protobuf.FieldCodec.ForString(10u, ""), global.Google.Protobuf.FieldCodec.ForMessage(18u, global.Google.Protobuf.FSharp.WellKnownTypes.Value.Parser), 10u)
type Value = {
    mutable _UnknownFields: global.Google.Protobuf.UnknownFieldSet
    mutable Kind: ValueOption<global.Google.Protobuf.FSharp.WellKnownTypes.Value.Types.Kind>
} with
    [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
    member me.Clone() : Value = {
        Value._UnknownFields = global.Google.Protobuf.UnknownFieldSet.Clone(me._UnknownFields)
        Value.Kind = me.Kind
    }
    [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
    member private me.InternalWriteTo(output: byref<global.Google.Protobuf.WriteContext>) =
        match me.Kind with
        | ValueNone -> ()
        | ValueSome (global.Google.Protobuf.FSharp.WellKnownTypes.Value.Types.Kind.NullValue x) ->
            output.WriteRawTag(8uy)
            output.WriteEnum(int x)
        | ValueSome (global.Google.Protobuf.FSharp.WellKnownTypes.Value.Types.Kind.NumberValue x) ->
            output.WriteRawTag(17uy)
            output.WriteDouble(x)
        | ValueSome (global.Google.Protobuf.FSharp.WellKnownTypes.Value.Types.Kind.StringValue x) ->
            output.WriteRawTag(26uy)
            output.WriteString(x)
        | ValueSome (global.Google.Protobuf.FSharp.WellKnownTypes.Value.Types.Kind.BoolValue x) ->
            output.WriteRawTag(32uy)
            output.WriteBool(x)
        | ValueSome (global.Google.Protobuf.FSharp.WellKnownTypes.Value.Types.Kind.StructValue x) ->
            output.WriteRawTag(42uy)
            output.WriteMessage(x)
        | ValueSome (global.Google.Protobuf.FSharp.WellKnownTypes.Value.Types.Kind.ListValue x) ->
            output.WriteRawTag(50uy)
            output.WriteMessage(x)
        if not <| isNull me._UnknownFields then me._UnknownFields.WriteTo(&output)
    [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
    member private me.CalculateSize() =
        let mutable size = 0
        match me.Kind with
        | ValueNone -> ()
        | ValueSome (global.Google.Protobuf.FSharp.WellKnownTypes.Value.Types.Kind.NullValue x) -> size <- size + 1 + global.Google.Protobuf.CodedOutputStream.ComputeEnumSize(int x)
        | ValueSome (global.Google.Protobuf.FSharp.WellKnownTypes.Value.Types.Kind.NumberValue x) -> size <- size + 9
        | ValueSome (global.Google.Protobuf.FSharp.WellKnownTypes.Value.Types.Kind.StringValue x) -> size <- size + 1 + global.Google.Protobuf.CodedOutputStream.ComputeStringSize(x)
        | ValueSome (global.Google.Protobuf.FSharp.WellKnownTypes.Value.Types.Kind.BoolValue x) -> size <- size + 2
        | ValueSome (global.Google.Protobuf.FSharp.WellKnownTypes.Value.Types.Kind.StructValue x) -> size <- size + 1 + global.Google.Protobuf.CodedOutputStream.ComputeMessageSize(x)
        | ValueSome (global.Google.Protobuf.FSharp.WellKnownTypes.Value.Types.Kind.ListValue x) -> size <- size + 1 + global.Google.Protobuf.CodedOutputStream.ComputeMessageSize(x)
        if not <| isNull me._UnknownFields then size <- size + me._UnknownFields.CalculateSize()
        size
    [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
    member private me.MergeFrom(other: Value) =
        if other.Kind <> ValueNone
        then me.Kind <- other.Kind
        me._UnknownFields <- global.Google.Protobuf.UnknownFieldSet.MergeFrom(me._UnknownFields, other._UnknownFields)
    [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
    member private me.InternalMergeFrom(input: byref<global.Google.Protobuf.ParseContext>) =
        let mutable tag = input.ReadTag()
        while tag <> 0u do
            match tag with
            | 8u ->
                let value = enum(input.ReadEnum()) : global.Google.Protobuf.FSharp.WellKnownTypes.NullValue
                me.Kind <- ValueSome(global.Google.Protobuf.FSharp.WellKnownTypes.Value.Types.Kind.NullValue(value))
            | 17u ->
                let value = input.ReadDouble()
                me.Kind <- ValueSome(global.Google.Protobuf.FSharp.WellKnownTypes.Value.Types.Kind.NumberValue(value))
            | 26u ->
                let value = input.ReadString()
                me.Kind <- ValueSome(global.Google.Protobuf.FSharp.WellKnownTypes.Value.Types.Kind.StringValue(value))
            | 32u ->
                let value = input.ReadBool()
                me.Kind <- ValueSome(global.Google.Protobuf.FSharp.WellKnownTypes.Value.Types.Kind.BoolValue(value))
            | 42u ->
                let value = global.Google.Protobuf.FSharp.WellKnownTypes.Struct.empty()
                input.ReadMessage(value)
                me.Kind <- ValueSome(global.Google.Protobuf.FSharp.WellKnownTypes.Value.Types.Kind.StructValue(value))
            | 50u ->
                let value = global.Google.Protobuf.FSharp.WellKnownTypes.ListValue.empty()
                input.ReadMessage(value)
                me.Kind <- ValueSome(global.Google.Protobuf.FSharp.WellKnownTypes.Value.Types.Kind.ListValue(value))
            | _ ->
                me._UnknownFields <- global.Google.Protobuf.UnknownFieldSet.MergeFieldFrom(me._UnknownFields, &input)
            tag <- input.ReadTag()
    interface global.Google.Protobuf.IBufferMessage with
        [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
        member me.InternalMergeFrom(ctx) = me.InternalMergeFrom(&ctx)
        [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
        member me.InternalWriteTo(ctx) = me.InternalWriteTo(&ctx)
    interface global.Google.Protobuf.IMessage<Value> with
        [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
        member me.Clone() = me.Clone()
        [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
        member me.MergeFrom(other) = me.MergeFrom(other)
    interface global.Google.Protobuf.IMessage with
        [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
        member me.CalculateSize() = me.CalculateSize()
        [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
        member me.MergeFrom(input) = input.ReadRawMessage(me)
        [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
        member me.WriteTo(output) = output.WriteRawMessage(me)
        [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
        member __.Descriptor = global.Google.Protobuf.FSharp.WellKnownTypes.StructReflection.Value_Descriptor()
module Value =
    [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
    let internal DefaultValue = {
        Value._UnknownFields = null
        Value.Kind = ValueNone
    }
    [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
    let empty () = {
        Value._UnknownFields = null
        Value.Kind = ValueNone
    }
    [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
    let Parser = global.Google.Protobuf.MessageParser<Value>(global.System.Func<_>(empty))
    let NullValueFieldNumber = 1
    let NumberValueFieldNumber = 2
    let StringValueFieldNumber = 3
    let BoolValueFieldNumber = 4
    let StructValueFieldNumber = 5
    let ListValueFieldNumber = 6
    module Types =
        type Kind =
        | NullValue of global.Google.Protobuf.FSharp.WellKnownTypes.NullValue
        | NumberValue of float
        | StringValue of string
        | BoolValue of bool
        | StructValue of global.Google.Protobuf.FSharp.WellKnownTypes.Struct
        | ListValue of global.Google.Protobuf.FSharp.WellKnownTypes.ListValue
type ListValue = {
    mutable _UnknownFields: global.Google.Protobuf.UnknownFieldSet
    Values: global.Google.Protobuf.Collections.RepeatedField<global.Google.Protobuf.FSharp.WellKnownTypes.Value>
} with
    [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
    member me.Clone() : ListValue = {
        ListValue._UnknownFields = global.Google.Protobuf.UnknownFieldSet.Clone(me._UnknownFields)
        ListValue.Values = me.Values.Clone()
    }
    [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
    member private me.InternalWriteTo(output: byref<global.Google.Protobuf.WriteContext>) =
        me.Values.WriteTo(&output, ListValue.RepeatedValuesCodec)
        if not <| isNull me._UnknownFields then me._UnknownFields.WriteTo(&output)
    [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
    member private me.CalculateSize() =
        let mutable size = 0
        size <- size + me.Values.CalculateSize(ListValue.RepeatedValuesCodec)
        if not <| isNull me._UnknownFields then size <- size + me._UnknownFields.CalculateSize()
        size
    [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
    member private me.MergeFrom(other: ListValue) =
        me.Values.Add(other.Values)
        me._UnknownFields <- global.Google.Protobuf.UnknownFieldSet.MergeFrom(me._UnknownFields, other._UnknownFields)
    [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
    member private me.InternalMergeFrom(input: byref<global.Google.Protobuf.ParseContext>) =
        let mutable tag = input.ReadTag()
        while tag <> 0u do
            match tag with
            | 10u ->
                me.Values.AddEntriesFrom(&input,ListValue.RepeatedValuesCodec)
            | _ ->
                me._UnknownFields <- global.Google.Protobuf.UnknownFieldSet.MergeFieldFrom(me._UnknownFields, &input)
            tag <- input.ReadTag()
    interface global.Google.Protobuf.IBufferMessage with
        [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
        member me.InternalMergeFrom(ctx) = me.InternalMergeFrom(&ctx)
        [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
        member me.InternalWriteTo(ctx) = me.InternalWriteTo(&ctx)
    interface global.Google.Protobuf.IMessage<ListValue> with
        [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
        member me.Clone() = me.Clone()
        [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
        member me.MergeFrom(other) = me.MergeFrom(other)
    interface global.Google.Protobuf.IMessage with
        [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
        member me.CalculateSize() = me.CalculateSize()
        [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
        member me.MergeFrom(input) = input.ReadRawMessage(me)
        [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
        member me.WriteTo(output) = output.WriteRawMessage(me)
        [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
        member __.Descriptor = global.Google.Protobuf.FSharp.WellKnownTypes.StructReflection.ListValue_Descriptor()
module ListValue =
    [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
    let internal DefaultValue = {
        ListValue._UnknownFields = null
        ListValue.Values = global.Google.Protobuf.Collections.RepeatedField<global.Google.Protobuf.FSharp.WellKnownTypes.Value>()
    }
    [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
    let empty () = {
        ListValue._UnknownFields = null
        ListValue.Values = global.Google.Protobuf.Collections.RepeatedField<global.Google.Protobuf.FSharp.WellKnownTypes.Value>()
    }
    [<global.System.Diagnostics.DebuggerNonUserCodeAttribute>]
    let Parser = global.Google.Protobuf.MessageParser<ListValue>(global.System.Func<_>(empty))
    let ValuesFieldNumber = 1
    let RepeatedValuesCodec = global.Google.Protobuf.FieldCodec.ForMessage(10u, global.Google.Protobuf.FSharp.WellKnownTypes.Value.Parser)
// End of auto-generated code
